# Generated by Django 4.2.1 on 2023-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_delete_age_delete_diagnosis_delete_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
